FROM python:3.11-slim

# Устанавливаем зависимости
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Устанавливаем рабочую директорию
WORKDIR /usr/src/app

# Копируем requirements.txt
COPY requirements.txt .

# Устанавливаем зависимости для Flask
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь проект
COPY . .

# Ожидаем запуска приложения Flask
CMD ["python", "app.py"]
