FROM python:3.11-slim

# Устанавливаем зависимости для Flask и CMake
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    cmake \
    g++ \
    make \
    && rm -rf /var/lib/apt/lists/*

# Указываем рабочую директорию внутри контейнера
WORKDIR /usr/src/app

# Копируем файл зависимостей
COPY requirements.txt .

# Устанавливаем зависимости из requirements.txt
RUN pip install --no-cache-dir --prefer-binary -r requirements.txt

# Копируем все файлы из текущей директории в контейнер
COPY . .

# Открываем порт для Flask
EXPOSE 5001

# Указываем команду для запуска Flask
CMD ["python", "app.py"]
